export const keypadOptions = [
  { type: 'clearValue', value: 'C' },
  { type: 'digit', value: '7' },
  { type: 'digit', value: '8' },
  { type: 'digit', value: '9' },
  { type: 'operand', value: '*' },
  { type: 'operand', value: '-' },
  { type: 'digit', value: '4' },
  { type: 'digit', value: '5' },
  { type: 'digit', value: '6' },
  { type: 'operand', value: '/' },
  { type: 'operand', value: '+' },
  { type: 'digit', value: '1' },
  { type: 'digit', value: '2' },
  { type: 'digit', value: '3' },
  { type: 'result', value: '=' },
  { type: 'dot', value: '.' },
  { type: 'leftBracket', value: '(' },
  { type: 'digit', value: '0' },
  { type: 'rightBracket', value: ')' },
  { type: 'clearExp', value: 'CE' },
  { type: 'operand', value: '%' },
  { type: 'negate', value: '+/-' },
]
